language: python
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
# see: https://github.com/travis-ci/travis-ci/issues/9815
#matrix:
#  include:
python: 
  - 3.6
'''    - python: 3.7
    - python: 3.8
    - python: 3.9
      dist: xenial
      sudo: true
'''
before_install:
  - env
  - whoami
  - cat /etc/issue
  - export BOTO_CONFIG=/dev/null
install:
  - pip install -r test_requirements.txt
  #- pip install https://github.com/ashleygould/moto/archive/development.zip
  #- pip install https://github.com/spulec/moto/archive/master.zip
  - pip install .
  - pip list
script: 
  - flake8 orgtiger
  - pytest


