language: python
python: 
  - 3.6
before_install:
  - whoami
  - cat /etc/issue
  - export BOTO_CONFIG=/dev/null
install:
  - pip install -r test_requirements.txt
  - pip install .
  - pip list
script: 
  - flake8 orgtiger
  - pytest
